// Generated by https://quicktype.io

export interface UserModel {
    _id: string;
    otp: number;
    email: string;
    provider: string;
    proPlayer: boolean;
    superAdmin: boolean;
    current_balance: number;
    status: string;
    __v: number;
}
